export enum VEST {
  VEST_ESTATUS__AGENDADA = '0',
  VEST_ESTATUS__AGUARDANDO = '6',
  VEST_ESTATUS__APROVADA = '4',
  VEST_ESTATUS__CANCELADA = '2',
  VEST_ESTATUS__CHECKLIST_FINALIZADO = '8',
  VEST_ESTATUS__CHECKLIST_INICIADO = '7',
  VEST_ESTATUS__EFETIVADA = '1',
  VEST_ESTATUS__FINALIZADA = '5',
  VEST_ESTATUS__REJEITADA = '3',
}
